### ISSUE TITLE
US1 Display List Entries

### ISSUE THREAD

**Issue by mrrubinello** [mrrubinello/Capstone#2]
## Value Proposition

As a user,
I want to view a list of To-Do's,
in order to get an overview of my pending tasks and stay organized.

## Description

![Opera Momentaufnahme_2023-07-19_213820_miro com](https://github.com/mrrubinello/Capstone/assets/35063133/0a7de487-82b6-43c6-b2ea-79d9a4666be0)

## Acceptance Criteria#

- [ ] title is displayed
- [ ] each list entry from the array is displayed 

## Tasks

- [ ] create a feature branch
- [ ] create a component for the To Do List
- [ ] create an array with dummy data (array contains To Do´s)
- [ ] create a To Do Component
- [ ] render the To Do Component inside the To Do List Component
- [ ] render each list entry of the To Do List by using the Map function

**Comment by Roland-Hufnagel** [comment]
Hi Ruben, please think once more about userstories and maybe have a look at the handout. I have some comments: 
- you should not describe your app here, instead only the first issue, what is to be done
- First think about the MVP, and then make 2-3 Userstories, that describe the corresponding issues
- Please use the markdown format, that is given in the template (e.g. headers and checkboxes)

To give you an idea:
The MVP could be: The user can create tasks and view them in a list
Therefore you can write some userstories, e.g.
US1: Render a list of tasks (using dummy data)
US2: Show Detail Page
US3: Edit a task
US4: Create a new tasks

Then use the given template (and the format inside) to fill the userstory with a title, a value proposition, a description, some acceptance-criterias and the corresponding tasks, that belong only to that userstory.

Then update it in the slack channel

**Comment by Roland-Hufnagel** [comment]
Hey Ruben, this looks like a really good userstory now. Great 💪. I only have two minor things, I want you to adapt:
- Don't tell in the description about what you envision your app to do - better describe only what it can do at this point (even only the wireframe would be okay)
- I would recommend not only create a List Component but also a Todo Component (that is rendered inside the List Component)

**Comment by Roland-Hufnagel** [comment]
Now it looks great 🎉
