### ISSUE TITLE
US2 Adding a Form

### ISSUE THREAD

**Issue by mrrubinello** [mrrubinello/Capstone#3]
## Value Proposition

As a User,
I want to be able to add new tasks
so that I get to Form where I can add data for a list entry

## Description

<img width="640" alt="Bildschirmfoto 2023-07-25 um 15 16 59" src="https://github.com/mrrubinello/Capstone/assets/35063133/2f70beac-7ec2-4351-8b52-9372fb8764ee">

## Acceptance Criteria

- [ ]  an 'add' Button is visible 
- [ ] clicking the add-button leads to a form (symbolized here by an Arrow)
- [ ] on the form page is a Save-Button 
- [ ] Clicking the Save Button will save the form data and lead to the Homepage
- [ ] a link is visible that leads back to the homepage
- [ ] Form is displayed with a textfield
- [ ] Form content is saved
- [ ] Form content is displayed in the list
      ​

## Tasks

- [ ] create a form
- [ ] store the Data in an Array
- [ ] create an Add-Button 
- [ ] Create a Save Button
- [ ] create a link that directs to the form page
- [ ] create a submit handler that saves the form data locally
- [ ] create a "going back" button at the form page
- [ ] link the button to the homepage

**Comment by HannesOster** [comment]
Hey Ruben,

This looks good for first but: 
I would say that you could be a little more detailed, for example: which parts should the form have? Also i see buttons/icons on the wireframe which are not mentioned in the acceptance criteria or the tasks. 
In the tasks i would make a decision what youre gonna do: database or local storage? 
I would recommend you to use local storage for the beginning. 

See you later :)

**Comment by Roland-Hufnagel** [comment]
Hi Ruben.
In the value proposition please use the predefined format. The part '... in order to...' is missing.
``"adding a task button (+)" directs me to a new page with a form field (phone on the right)``is not a good description. Instead you can say more precise: ``- an 'add' Button is visible`` ``-clicking the add-button leads to a form`` ``-on the form page is a Save-Button`` ``Clicking the Save Button will save the form data and lead to the Homepage``

This is a medium-size US. Not a small one. So you can add some tasks like ``-create an Add-Button`` ``-Create a Save Button`` ``create a submit handler that saves the form data locally``

In your wireframe there is an arrow at the second picture at the bottom. Tell something about it. Acceptance Criteria: ``- A link is visible that leads back to the homepage``, don't forget to write a task for this.

**Comment by ekat-br** [comment]
Hi Ruben, 

please read again the feedback from Roland: _In your wireframe there is an arrow at the second picture at the bottom. Tell something about it. Acceptance Criteria: - A link is visible that leads back to the homepage, don't forget to write a task for this._ It looks like you forgot the task for it.

Apart from that it lgtm🚀

**Comment by ekat-br** [comment]
LGTM
