### ISSUE TITLE
US3 - Edit List Entries

### ISSUE THREAD

**Issue by mrrubinello** [mrrubinello/Capstone#4]
## Value Proposition

As a user,
i want to edit tasks in a detailed page
so that I can delete content from list entries

## Description

![Image](https://github.com/mrrubinello/Capstone/assets/35063133/8d742c11-d1b9-4151-a5b8-46cd71a99438)

## Acceptance Criteria

- [ ] Content is displayed in a Form field
- [ ] Form data is able to be deleted
- [ ] Pressing delete will remove the task 

## Tasks

- [ ] use the already existing form component from US2
- [ ] create a "delete button" containing the option to delete the data / task

**Comment by Roland-Hufnagel** [comment]
Please have a look again at the value proposition (as I mentioned in the last US).
I strongly recommend to first write a userstory to only see a Detailpage of your todo. Afterwards you can write userfunctions to edit the todo and to delete the todo.

**Comment by Roland-Hufnagel** [comment]
Just to have three buttons will not make this feature work. Please give some more details to the tasks and acceptance-criteria, e.g. 'Clicking the edit-button will open a form with the corresponding data.', 'Pressing delete will remove the task an a message is shown'
Tasks could be 'create a form (or a form component)', 'create a function "handleDelete" that removes the task from the list'

**Comment by Roland-Hufnagel** [comment]
LGTM
